In [1]:
#matrix convolution
import numpy as np

# Define the input matrix
input_matrix = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

# Define the kernel (filter) matrix
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]])

# Perform convolution
result = np.zeros_like(input_matrix)

# Get dimensions of input and kernel
input_shape = input_matrix.shape
kernel_shape = kernel.shape

# Perform convolution
for i in range(input_shape[0] - kernel_shape[0] + 1):
    for j in range(input_shape[1] - kernel_shape[1] + 1):
        result[i, j] = np.sum(input_matrix[i:i+kernel_shape[0], j:j+kernel_shape[1]] * kernel)

# Print the result
print("Input Matrix:")
print(input_matrix)
print("\nKernel Matrix:")
print(kernel)
print("\nResult after Convolution:")
print(result)


Input Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel Matrix:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Result after Convolution:
[[-6  0  0]
 [ 0  0  0]
 [ 0  0  0]]


In [2]:
import numpy as np

# Define your matrix
matrix = np.array([[1, 2, 3],
                   [4, 8, 12],
                   [1.5, 3, 4.5]])

# Find the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 1


In [3]:
import numpy as np

def least_squares(X, Y):
    n = len(X)
    
    # Calculate the mean of X and Y
    mean_x = np.mean(X)
    mean_y = np.mean(Y)
    
    # Calculate the slope (m) and intercept (b) using least squares method
    numerator = sum((X - mean_x) * (Y - mean_y))
    denominator = sum((X - mean_x) ** 2)
    m = numerator / denominator
    b = mean_y - m * mean_x
    
    return m, b

# Example usage
X = np.array([0,1, 2, 3, 4, 5])
Y = np.array([1,2, 1, 4, 5, 10])

slope, intercept = least_squares(X, Y)
print("Slope:", slope)
print("Intercept:", intercept)


Slope: 1.6285714285714286
Intercept: -0.2380952380952377


In [4]:
import numpy as np

def calculate_area(x1, y1, z1, x2, y2, z2, x3, y3, z3):
    # Define vectors
    v1 = np.array([x2 - x1, y2 - y1, z2 - z1])
    v2 = np.array([x3 - x1, y3 - y1, z3 - z1])

    # Calculate the cross product
    cross_product = np.cross(v1, v2)

    # Calculate the area of the parallelogram formed by the vectors
    area = np.linalg.norm(cross_product) / 2

    return area

# Example points
x1, y1, z1 = 1, 0, -3
x2, y2, z2 = 0, -2, -4
x3, y3, z3 = 4, 1, 6

# Calculate the area
area = calculate_area(x1, y1, z1, x2, y2, z2, x3, y3, z3)
print("Area of the triangle:", area)


Area of the triangle: 9.354143466934854


In [6]:
lst= {"a":10}
dist ={i:lst for i in lst }
print(dist)
    

{'a': {'a': 10}}
